site_name: sose
repo_url: https://github.com/pikld/sose
site_url: https://pikld.github.io/sose
site_description: Spatial ops on **SO/SE** — a tiny, fast 2D/3D Lie-group toolkit for robotics
site_author: pikld
edit_uri: edit/main/docs/
repo_name: pikld/sose
copyright: Maintained by <a href="https://pikld.com">pikld</a>.

nav:
  - Home: index.md
  - Modules: modules.md

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: numpy
            show_source: true
            members_order: source
            separate_signature: true
            show_root_heading: true
            show_category_heading: true
  - gen-files:
      scripts:
        - scripts/docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index

theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pikld/sose
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/sose

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
